# Generated by Django 3.0.3 on 2020-06-11 03:28

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(max_length=200, unique=True)),
                ('precio', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=food.models.direccion_imagenes_comida)),
            ],
        ),
        migrations.CreateModel(
            name='CantidadAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=5, validators=[food.models.numeric])),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=food.models.direccion_imagenes_comida)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, validators=[food.models.unique_status])),
            ],
        ),
        migrations.CreateModel(
            name='OrdenComida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(null=True, validators=[food.models.grade])),
                ('alimentos', models.ManyToManyField(related_name='articulos', through='food.CantidadAlimento', to='food.Alimento')),
            ],
        ),
    ]
