# Generated by Django 3.0.5 on 2020-05-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomida',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencomida',
            name='id_repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencomida',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Status'),
        ),
        migrations.AddField(
            model_name='cantidadalimento',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidad_alimento', to='food.Alimento'),
        ),
        migrations.AddField(
            model_name='cantidadalimento',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidad_alimento', to='food.OrdenComida'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Categoria'),
        ),
    ]
