# Generated by Django 3.0.3 on 2020-06-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200613_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadalimento',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='food.OrdenComida'),
        ),
    ]
