# Generated by Django 3.0.5 on 2020-05-08 01:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ap_paterno', models.CharField(max_length=110)),
                ('ap_materno', models.CharField(blank=True, max_length=110)),
                ('correo', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=60)),
                ('numero_lt', models.CharField(max_length=5)),
                ('numero_mz', models.CharField(max_length=5)),
                ('numero_interior', models.CharField(blank=True, max_length=5)),
                ('colonia', models.CharField(max_length=40)),
                ('delegacion', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ap_paterno', models.CharField(max_length=110)),
                ('ap_materno', models.CharField(blank=True, max_length=110)),
                ('correo', models.EmailField(max_length=300)),
                ('telefono', models.CharField(max_length=20, validators=[users.models.numero_telefono])),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ap_paterno', models.CharField(max_length=110)),
                ('ap_materno', models.CharField(blank=True, max_length=110)),
                ('correo', models.EmailField(max_length=300)),
                ('telefono', models.CharField(max_length=20, validators=[users.models.numero_telefono])),
                ('direccion', models.ManyToManyField(related_name='direcciones', to='users.Direcciones')),
            ],
        ),
    ]
