# Generated by Django 3.0.3 on 2020-06-13 23:09

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ap_materno',
            field=models.CharField(blank=True, error_messages={'max_length': 'Tu apellido debe teer 110 caracteres máximo'}, max_length=110),
        ),
        migrations.AlterField(
            model_name='account',
            name='ap_paterno',
            field=models.CharField(error_messages={'max_length': 'Tu apellido debe teer 110 caracteres máximo', 'required': 'Necesitas escribir un appelido'}, max_length=110),
        ),
        migrations.AlterField(
            model_name='account',
            name='correo',
            field=models.EmailField(error_messages={'invalid': 'Necesitas escribir un email valido', 'max_length': 'Tu email solo puede tener 300 caracteres máximo', 'required': 'Es necesario dar un email', 'unique': 'Este email ya esta en uso'}, max_length=300, unique=True, validators=[django.core.validators.EmailValidator(message='Necesitas escribir un email valido')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'Tu nombre debe teer 80 caracteres máximo', 'required': 'Necesitas escribir un nombre'}, max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='telefono',
            field=models.CharField(blank=True, error_messages={'max_length': 'Tu email solo puede tener 300 caracteres máximo', 'required': 'Es necesario dar un email'}, help_text='Escribe numeros sin espacio Ej 5522009117', max_length=20, validators=[users.models.numero_telefono]),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='calle',
            field=models.CharField(error_messages={'max_length': 'La calle puede tener 60 caracteres maximo', 'required': 'Es necesario dar una calle'}, max_length=60),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='cp',
            field=models.CharField(error_messages={'max_length': 'El codigo postal puede tener 10 caracteres maximo', 'required': 'Es necesario dar un codigo postal'}, max_length=10, validators=[users.models.numeros]),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='numero_interior',
            field=models.CharField(blank=True, error_messages={'max_length': 'La longitud máxima es e 5 caracteres'}, max_length=5, validators=[users.models.numeros]),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='numero_lt',
            field=models.CharField(error_messages={'max_length': 'La longitud máxima es de 5 caracteres', 'required': 'Este campo es obligatorio'}, max_length=5, validators=[users.models.numeros]),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='numero_mz',
            field=models.CharField(error_messages={'max_length': 'La longitud máxima es de 5 caracteres', 'required': 'Este campo es obligatorio'}, max_length=5, validators=[users.models.numeros]),
        ),
    ]
