# Generated by Django 3.0.3 on 2020-06-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200613_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='correo',
            field=models.EmailField(error_messages={'invalid': 'Necesitas escribir un email valido', 'max_length': 'Tu email solo puede tener 300 caracteres máximo', 'required': 'Es necesario dar un email', 'unique': 'Este email ya esta en uso'}, max_length=300, unique=True),
        ),
    ]
