# Generated by Django 3.0.3 on 2020-06-14 14:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200613_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='correo',
            field=models.EmailField(error_messages={'invalid': 'Necesitas escribir un email valido', 'max_length': 'Tu email solo puede tener 150 caracteres máximo', 'required': 'Es necesario dar un email', 'unique': 'Este email ya esta en uso'}, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telefono',
            field=models.CharField(blank=True, error_messages={'max_length': 'Tu email solo puede tener 20 caracteres máximo', 'required': 'Es necesario dar un email'}, help_text='Escribe numeros sin espacio Ej 5522009117', max_length=20, validators=[users.models.numero_telefono]),
        ),
    ]
